/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());

    /**
     * Creates new form menu
     */
    int quantity = 0;
    
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnswd = new javax.swing.JButton();
        txtsw = new javax.swing.JTextField();
        btnswi = new javax.swing.JButton();
        btndd = new javax.swing.JButton();
        txtd = new javax.swing.JTextField();
        btndi = new javax.swing.JButton();
        sandwich = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        btnfi = new javax.swing.JButton();
        txtf = new javax.swing.JTextField();
        btnfd = new javax.swing.JButton();
        fries = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        burger = new javax.swing.JCheckBox();
        btnbmi = new javax.swing.JButton();
        txtbm = new javax.swing.JTextField();
        btnbmd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        spag = new javax.swing.JCheckBox();
        btnsi = new javax.swing.JButton();
        txts = new javax.swing.JTextField();
        btnsd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        milkshake = new javax.swing.JCheckBox();
        txtms = new javax.swing.JTextField();
        btnmsi = new javax.swing.JButton();
        btnmsd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        water = new javax.swing.JCheckBox();
        btnwi = new javax.swing.JButton();
        txtw = new javax.swing.JTextField();
        btnwd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cookie = new javax.swing.JCheckBox();
        txtc = new javax.swing.JTextField();
        btnci = new javax.swing.JButton();
        btncd = new javax.swing.JButton();
        donut = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        btn1.setBackground(new java.awt.Color(255, 204, 153));
        btn1.setText("Menu");
        btn1.addActionListener(this::btn1ActionPerformed);

        jButton2.setText("Student Order");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Sales Report");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton1.setText("Inventory");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, -1));

        btnswd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnswd.setText("-");
        btnswd.addActionListener(this::btnswdActionPerformed);
        getContentPane().add(btnswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 519, -1, -1));

        txtsw.addActionListener(this::txtswActionPerformed);
        getContentPane().add(txtsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 522, 40, -1));

        btnswi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnswi.setText("+");
        btnswi.addActionListener(this::btnswiActionPerformed);
        getContentPane().add(btnswi, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 519, -1, -1));

        btndd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndd.setText("-");
        btndd.addActionListener(this::btnddActionPerformed);
        getContentPane().add(btndd, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 519, -1, -1));

        txtd.addActionListener(this::txtdActionPerformed);
        getContentPane().add(txtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 522, 40, -1));

        btndi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndi.setText("+");
        btndi.addActionListener(this::btndiActionPerformed);
        getContentPane().add(btndi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 519, -1, -1));

        sandwich.setText("Sandwich");
        sandwich.addActionListener(this::sandwichActionPerformed);
        getContentPane().add(sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 493, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sandwich.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 387, -1, -1));

        btnfi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnfi.setText("+");
        btnfi.addActionListener(this::btnfiActionPerformed);
        getContentPane().add(btnfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 345, -1, -1));

        txtf.addActionListener(this::txtfActionPerformed);
        getContentPane().add(txtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 345, 39, -1));

        btnfd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnfd.setText("-");
        btnfd.addActionListener(this::btnfdActionPerformed);
        getContentPane().add(btnfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 345, -1, -1));

        fries.setText("Fries");
        fries.addActionListener(this::friesActionPerformed);
        getContentPane().add(fries, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/63cc6125-023e-4627-8818-89a34370 (1).jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 100));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 99, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Meals");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Canteen Ordering System");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 607, 41));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(175, 470));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/set meal.jpg"))); // NOI18N

        burger.setText("Burger Meal");
        burger.addActionListener(this::burgerActionPerformed);

        btnbmi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbmi.setText("+");
        btnbmi.addActionListener(this::btnbmiActionPerformed);

        txtbm.addActionListener(this::txtbmActionPerformed);

        btnbmd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbmd.setText("-");
        btnbmd.addActionListener(this::btnbmdActionPerformed);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/spaghetti.jpg"))); // NOI18N

        spag.setText("Spaghetti");
        spag.addActionListener(this::spagActionPerformed);

        btnsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsi.setText("+");
        btnsi.addActionListener(this::btnsiActionPerformed);

        txts.addActionListener(this::txtsActionPerformed);

        btnsd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsd.setText("-");
        btnsd.addActionListener(this::btnsdActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(burger))
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnbmd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbmi))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnsd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsi))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(spag)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(burger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbmi)
                    .addComponent(txtbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbmd))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsi)
                    .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsd))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 175, 470));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(175, 470));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/milkshake.jpg"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Drinks");

        milkshake.setText("Milkshake");
        milkshake.addActionListener(this::milkshakeActionPerformed);

        txtms.addActionListener(this::txtmsActionPerformed);

        btnmsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmsi.setText("+");
        btnmsi.addActionListener(this::btnmsiActionPerformed);

        btnmsd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmsd.setText("-");
        btnmsd.addActionListener(this::btnmsdActionPerformed);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/water.jpg"))); // NOI18N

        water.setText("Water");
        water.addActionListener(this::waterActionPerformed);

        btnwi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnwi.setText("+");
        btnwi.addActionListener(this::btnwiActionPerformed);

        txtw.addActionListener(this::txtwActionPerformed);

        btnwd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnwd.setText("-");
        btnwd.addActionListener(this::btnwdActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnwi))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(milkshake)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(btnmsd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtms, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnmsi))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(water)
                                .addComponent(jLabel8)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(milkshake)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmsi)
                    .addComponent(btnmsd))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(water)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnwi)
                    .addComponent(txtw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwd))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 175, 470));

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(175, 470));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Snacks");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 175, 470));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Treats");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cookies.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/donut.jpg"))); // NOI18N

        cookie.setText("Cookie");
        cookie.addActionListener(this::cookieActionPerformed);

        txtc.addActionListener(this::txtcActionPerformed);

        btnci.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnci.setText("+");
        btnci.addActionListener(this::btnciActionPerformed);

        btncd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncd.setText("-");
        btncd.addActionListener(this::btncdActionPerformed);

        donut.setText("Donut");
        donut.addActionListener(this::donutActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btncd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnci))
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cookie)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(donut)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cookie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncd)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnci))
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donut)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 170, 470));

        jPanel6.setBackground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        studentorder sorder = new studentorder();
        sorder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        menu menu1 = new menu();
        menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmsActionPerformed
        // TODO add your handling code here:
            txtms.setText("0");
            txtms.setEditable(false);
    }//GEN-LAST:event_txtmsActionPerformed

    private void btnmsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmsiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtms.setText(String.valueOf (quantity));
        }
        else {
           txtms.setText("Max");
        }
        btnmsi.setEnabled(true);
    }//GEN-LAST:event_btnmsiActionPerformed

    private void btnmsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmsdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtms.setText(String.valueOf(quantity));
        }
        btnmsd.setEnabled(true);
    }//GEN-LAST:event_btnmsdActionPerformed

    private void milkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkshakeActionPerformed
        // TODO add your handling code here:
        
        boolean selected = 
                milkshake.isSelected();
        btnmsi.setEnabled(selected);
        btnmsd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtms.setText("0");
                
        }
    }//GEN-LAST:event_milkshakeActionPerformed

    private void txtbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbmActionPerformed
        // TODO add your handling code here:
        txtbm.setText("0");
        txtbm.setEditable(false);
    }//GEN-LAST:event_txtbmActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        // TODO add your handling code here:
        boolean selected = 
                burger.isSelected();
        btnbmi.setEnabled(selected);
        btnbmd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtbm.setText("0");
        }
    }//GEN-LAST:event_burgerActionPerformed

    private void btnbmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbmdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtbm.setText(String.valueOf(quantity));
        }
        btnbmd.setEnabled(true);
    }//GEN-LAST:event_btnbmdActionPerformed

    private void btnbmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbmiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtbm.setText(String.valueOf (quantity));
        }
        else {
           txtbm.setText("Max");
        }
        btnbmi.setEnabled(true);
    }//GEN-LAST:event_btnbmiActionPerformed

    private void friesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friesActionPerformed
        // TODO add your handling code here:
        boolean selected = 
                fries.isSelected();
        btnfi.setEnabled(selected);
        btnfd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtf.setText("0");
        }
    }//GEN-LAST:event_friesActionPerformed

    private void btnfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtf.setText(String.valueOf(quantity));
        }
        btnfd.setEnabled(true);
    }//GEN-LAST:event_btnfdActionPerformed

    private void btnfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtf.setText(String.valueOf (quantity));
        }
        else {
           txtf.setText("Max");
        }
        btnfi.setEnabled(true);
    }//GEN-LAST:event_btnfiActionPerformed

    private void txtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfActionPerformed
        // TODO add your handling code here:
        txtf.setText("0");
        txtf.setEditable(false);
    }//GEN-LAST:event_txtfActionPerformed

    private void cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieActionPerformed
        // TODO add your handling code here:
        boolean selected = 
                cookie.isSelected();
        btnci.setEnabled(selected);
        btncd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtc.setText("0");
        }
    }//GEN-LAST:event_cookieActionPerformed

    private void btncdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtc.setText(String.valueOf(quantity));
        }
        btncd.setEnabled(true);
    }//GEN-LAST:event_btncdActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
        txtc.setText("0");
        txtc.setEditable(false);
    }//GEN-LAST:event_txtcActionPerformed

    private void btnciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnciActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtc.setText(String.valueOf (quantity));
        }
        else {
           txtc.setText("Max");
        }
        btnci.setEnabled(true);
    }//GEN-LAST:event_btnciActionPerformed

    private void waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterActionPerformed
        // TODO add your handling code here:
        boolean selected = 
                water.isSelected();
        btnwi.setEnabled(selected);
        btnwd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtw.setText("0");
        }
    }//GEN-LAST:event_waterActionPerformed

    private void btnwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtw.setText(String.valueOf(quantity));
        }
        btnwd.setEnabled(true);
    }//GEN-LAST:event_btnwdActionPerformed

    private void txtwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwActionPerformed
        // TODO add your handling code here:
        txtw.setText("0");
        txtw.setEditable(false);
    }//GEN-LAST:event_txtwActionPerformed

    private void btnwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtw.setText(String.valueOf (quantity));
        }
        else {
           txtw.setText("Max");
        }
        btnwi.setEnabled(true);
    }//GEN-LAST:event_btnwiActionPerformed

    private void spagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spagActionPerformed
        // TODO add your handling code here:
        boolean selected = 
                spag.isSelected();
        btnsi.setEnabled(selected);
        btnsd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txts.setText("0");
        }
    }//GEN-LAST:event_spagActionPerformed

    private void btnsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txts.setText(String.valueOf(quantity));
        }
        btnsd.setEnabled(true);
    }//GEN-LAST:event_btnsdActionPerformed

    private void txtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsActionPerformed
        // TODO add your handling code here:
        txts.setText("0");
        txts.setEditable(false);
    }//GEN-LAST:event_txtsActionPerformed

    private void btnsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txts.setText(String.valueOf (quantity));
        }
        else {
           txts.setText("Max");
        }
        btnsi.setEnabled(true);
    }//GEN-LAST:event_btnsiActionPerformed

    private void sandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichActionPerformed
        // TODO add your handling code here:
         boolean selected = 
                sandwich.isSelected();
        btnswi.setEnabled(selected);
        btnswd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtsw.setText("0");
        }
    }//GEN-LAST:event_sandwichActionPerformed

    private void btnswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnswdActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtsw.setText(String.valueOf(quantity));
        }
        btnswd.setEnabled(true);
    }//GEN-LAST:event_btnswdActionPerformed

    private void txtswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtswActionPerformed
        // TODO add your handling code here:
        txtsw.setText("0");
        txtsw.setEditable(false);
    }//GEN-LAST:event_txtswActionPerformed

    private void btnswiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnswiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtsw.setText(String.valueOf (quantity));
        }
        else {
           txtsw.setText("Max");
        }
        btnswi.setEnabled(true);
    }//GEN-LAST:event_btnswiActionPerformed

    private void donutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donutActionPerformed
        // TODO add your handling code here:
        boolean selected = 
                donut.isSelected();
        btndi.setEnabled(selected);
        btndd.setEnabled(selected);
        
        if(!selected){
                quantity = 0;
                txtd.setText("0");
        }
    }//GEN-LAST:event_donutActionPerformed

    private void btnddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnddActionPerformed
        // TODO add your handling code here:
        if (quantity > 0){
        quantity--;
        txtd.setText(String.valueOf(quantity));
        }
        btndd.setEnabled(true);
    }//GEN-LAST:event_btnddActionPerformed

    private void txtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdActionPerformed
        // TODO add your handling code here:
        txtd.setText("0");
        txtd.setEditable(false);
    }//GEN-LAST:event_txtdActionPerformed

    private void btndiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiActionPerformed
        // TODO add your handling code here:
        if (quantity < 10 ){
        quantity++;
        txtd.setText(String.valueOf (quantity));
        }
        else {
           txtd.setText("Max");
        }
        btndi.setEnabled(true);
    }//GEN-LAST:event_btndiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new menu().setVisible(true);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnbmd;
    private javax.swing.JButton btnbmi;
    private javax.swing.JButton btncd;
    private javax.swing.JButton btnci;
    private javax.swing.JButton btndd;
    private javax.swing.JButton btndi;
    private javax.swing.JButton btnfd;
    private javax.swing.JButton btnfi;
    private javax.swing.JButton btnmsd;
    private javax.swing.JButton btnmsi;
    private javax.swing.JButton btnsd;
    private javax.swing.JButton btnsi;
    private javax.swing.JButton btnswd;
    private javax.swing.JButton btnswi;
    private javax.swing.JButton btnwd;
    private javax.swing.JButton btnwi;
    private javax.swing.JCheckBox burger;
    private javax.swing.JCheckBox cookie;
    private javax.swing.JCheckBox donut;
    private javax.swing.JCheckBox fries;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox milkshake;
    private javax.swing.JCheckBox sandwich;
    private javax.swing.JCheckBox spag;
    private javax.swing.JTextField txtbm;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextField txtf;
    private javax.swing.JTextField txtms;
    private javax.swing.JTextField txts;
    private javax.swing.JTextField txtsw;
    private javax.swing.JTextField txtw;
    private javax.swing.JCheckBox water;
    // End of variables declaration//GEN-END:variables
}
